#!/bin/bash

if [ ! -f "$OPENSHIFT_DATA_DIR"secrets.json ]; then
	echo "Generating $OPENSHIFT_DATA_DIR/secrets.json"
	python "$OPENSHIFT_REPO_DIR"libs/secrets.py > "$OPENSHIFT_DATA_DIR"secrets.json
fi


echo "Executing 'python $OPENSHIFT_REPO_DIR/manage.py migrate --noinput'"
python "$OPENSHIFT_REPO_DIR"/manage.py migrate --noinput


echo "Executing 'python $OPENSHIFT_REPO_DIR/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"/manage.py collectstatic --noinput
