# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import survey.utils

class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20160208_0356'),
    ]

    operations = [
            migrations.AlterField(
                model_name='group',
                name='code',
                field=models.CharField(default=survey.utils.generate_code, max_length=10, unique=True),
            ),
    ]
