# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20160208_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResponsePresave',
            fields=[
                ('testresponse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.TestResponse')),
                ('seconds_left', models.IntegerField(default=0, verbose_name='\u041e\u0441\u0442\u0430\u0432\u0448\u0435\u0435\u0441\u044f \u0432\u0440\u0435\u043c\u044f')),
            ],
            bases=('survey.testresponse',),
        ),
    ]
